RCL - RoboCLuedo: ArmorTools::ConnectAndLoad
ConnectAndLoad()
bool ArmorTools::ConnectAndLoad (std::string path, std::string uri = ARMOR_DEFAULT_URI, bool manipulationFlag = true, std::string reasoner = ARMOR_DEFAULT_REASONER, bool buffered_reasoner = true)
connect to the server and load the ontology from file.
Just a shortcut for the couple ArmorTools::Connect then ArmorTools::LoadOntology .
See also
ArmorTools::Connect connection to the aRMOR service
ArmorTools::LoadOntology loading ontology from file, and arguments
Returns
success or not
Examples
ArmorTools - 002 - The quickest way to use ArmorTools.
Definition at line 213 of file armor_tools.cpp.
References Connect(), and LoadOntology().
Referenced by ArmorCluedo::Init().