RCL - RoboCLuedo: ArmorCluedo::GetIndivOfClass
GetIndivOfClass()
std::vector< std::string > ArmorCluedo::GetIndivOfClass (std::string classname)
find the individuals belonging to a class
Parameters
classname the class
Returns
a vector of individals inside the class (eventually empty)
Warning
The element also returns the discarded hypotheses. Don't use this method for inspecting the hypotheses!
Examples
ArmorCluedo - 001 - Working on Individuals.
Definition at line 97 of file armor_cluedo.cpp.
References ARMOR_ERR, FilterVector(), ArmorTools::GetLastRes(), and ArmorTools::SendCommand().
Referenced by FindCompleteHypotheses(), and FindInconsistentHypotheses().