RCL - RoboCLuedo: ArmorTools::SendCommand
SendCommand()
bool ArmorTools::SendCommand (std::string command, std::string first_spec = "", std::string second_spec = "", std::string arg1 = "", std::string arg2 = "", std::string arg3 = "", std::string arg4 = "", std::string arg5 = "", bool printRequest = false)
fill in a command and send it to aRMOR
Shortcut for the couple ArmorTools::GetRequest and Armor::CallArmor.
Parameters
command (mandatory) the main command
first_spec (optional) the first specifier
second_spec (optional) the second specifier
arg (optional) (from 1 to 5) the arguments of the request
printResponse print the request before calling the service
Returns
success or not
Examples
ArmorTools - 001 - Essential usage of ArmorTools, and ArmorTools - 002 - The quickest way to use ArmorTools.
Definition at line 360 of file armor_tools.cpp.
References ARMOR_CHECK_INTERFACE, CallArmor(), GetRequest(), and PrintRequest().
Referenced by ArmorCluedo::AddIndiv(), ArmorCluedo::ExistsIndiv(), ArmorCluedo::GetClassOfIndiv(), ArmorCluedo::GetIndivOfClass(), ArmorCluedo::GetValuedOfIndiv(), and ArmorCluedo::SetObjectProperty().