RCL - RoboCLuedo: ArmorTools::GetRequest
GetRequest()
armor_msgs::ArmorDirective ArmorTools::GetRequest (std::string command, std::string first_spec = "", std::string second_spec = "", std::string arg1 = "", std::string arg2 = "", std::string arg3 = "", std::string arg4 = "", std::string arg5 = "")
quick generation of an aRMOR request
This function writes the aRMOR directive request in one shot.
Parameters
command (mandatory) the main command
first_spec (optional) the first specifier
second_spec (optional) the second specifier
arg (optional) (from 1 to 5) the arguments of the request
Returns
the complete aRMOR directve message with the request part ready to use.
See also
aRMOR table of commands
Examples
ArmorTools - 001 - Essential usage of ArmorTools.
Definition at line 82 of file armor_tools.cpp.
Referenced by LoadOntology(), SaveOntology(), SendCommand(), and UpdateOntology().