RCL - RoboCLuedo: ArmorTools::CallArmor
CallArmor()
bool ArmorTools::CallArmor (armor_msgs::ArmorDirective & data)
send a command to the aRMOR service.
This function performs the call to the aRMOR service ARMOR_SERVICE_SINGLE_REQUEST given the entire message to send to.
Parameters
data reference to the request to send
Returns
false if there's not coenction, or if the request went wrong. true otherwise.
Todo:
there's no way to compose aRMOR commands in a list. actually ARMOR_SERVICE_MULTIPLE_REQUESTS is unused.
Examples
ArmorTools - 001 - Essential usage of ArmorTools.
Definition at line 118 of file armor_tools.cpp.
References ARMOR_ERR, ARMOR_SERVICE_SINGLE_REQUEST, and LOGSQUARE.
Referenced by LoadOntology(), SaveOntology(), SendCommand(), and UpdateOntology().